# Generated by Django 4.2.2 on 2023-06-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khbswebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_reg',
            name='student_img',
            field=models.ImageField(null=True, upload_to='student_img/'),
        ),
    ]
