# Generated by Django 4.2 on 2023-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khbswebapp', '0002_student_reg_student_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_reg',
            name='student_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student_reg',
            name='student_img',
            field=models.ImageField(upload_to='student_img/'),
        ),
    ]
