# Generated by Django 4.2 on 2023-06-26 13:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('khbswebapp', '0004_remove_student_reg_student_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_reg',
            name='student_address_city',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student_reg',
            name='student_address_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student_reg',
            name='student_address_state',
            field=models.CharField(max_length=100),
        ),
    ]
