# Generated by Django 4.2 on 2023-06-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khbswebapp', '0005_alter_student_reg_student_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_info',
            name='father_img',
            field=models.ImageField(null=True, upload_to='reg-image/parent-image/'),
        ),
        migrations.AddField(
            model_name='parent_info',
            name='mother_img',
            field=models.ImageField(null=True, upload_to='reg-image/parent-image/'),
        ),
        migrations.AlterField(
            model_name='student_reg',
            name='student_img',
            field=models.ImageField(upload_to='reg-image/student-image/'),
        ),
    ]
