# Generated by Django 4.2 on 2023-06-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khbswebapp', '0006_parent_info_father_img_parent_info_mother_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_info',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='parent_info',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
