# Generated by Django 4.2 on 2023-06-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khbswebapp', '0007_parent_info_city_parent_info_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent_info',
            name='address',
        ),
    ]
