# Generated by Django 4.2.2 on 2023-06-30 02:58

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('course_img', models.ImageField(upload_to='media/programs')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
