# Generated by Django 4.2.2 on 2023-06-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khbs_online', '0002_program_delete_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='video_url',
        ),
    ]
