# Generated by Django 4.2.2 on 2023-07-02 02:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khbs_online', '0003_remove_program_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='course_img',
            field=models.ImageField(upload_to='programs/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos_uploaded/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_password', models.CharField(max_length=100)),
                ('user_img', models.ImageField(null=True, upload_to='user-images')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
