# Generated by Django 4.2.2 on 2023-07-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khbs_online', '0005_specialprogram_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='date_field',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='specialprogram',
            name='date_field',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user_course',
            name='date_field',
            field=models.DateField(auto_now=True),
        ),
    ]
