# Generated by Django 4.2.4 on 2023-08-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khbs_online', '0007_videoseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_img',
            field=models.ImageField(null=True, upload_to='profile-images'),
        ),
    ]
